export default [
  {
    title: 'Samsung Galaxy S9',
    description: 'Samsung Galaxy S9',
    unit_price: 1500,
    currency: '$',
    picture_url: 'https://username-mp-ecommerce-php.herokuapp.com/assets/images/samsung-galaxy-s9-xxl.jpg',
    id: '0001',
  },
  {
    title: 'LG G6',
    description: 'LG G6',
    unit_price: 1000,
    currency: '$',
    picture_url: 'https://username-mp-ecommerce-php.herokuapp.com/assets/images/l6g6.jpg',
    id: '0002',
  },
  {
    title: 'iPhone 8',
    description: 'iPhone 8',
    unit_price: 800,
    currency: '$',
    picture_url: 'https://username-mp-ecommerce-php.herokuapp.com/assets/images/u_10168742.jpg',
    id: '0003',
  },
  {
    title: 'Motorola G5',
    description: 'Motorola G5',
    unit_price: 900,
    currency: '$',
    picture_url: 'https://username-mp-ecommerce-php.herokuapp.com/assets/images/motorola-moto-g5-plus-1.jpg',
    id: '0004',
  },
  {
    title: 'Moto G4',
    description: 'Moto G4',
    unit_price: 300,
    currency: '$',
    picture_url: 'https://username-mp-ecommerce-php.herokuapp.com/assets/images/motorola-moto-g4-3.jpg',
    id: '0005',
  },
  {
    title: 'Sony XPeria ZX2',
    description: 'Sony XPeria ZX2',
    unit_price: 1000,
    currency: '$',
    picture_url: 'https://username-mp-ecommerce-php.herokuapp.com/assets/images/003.jpg',
    id: '0006',
  },
];
